name: recu_drive
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.3
  clipboard: ^0.1.3
  fluttertoast: ^8.0.8
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.3+1
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/


